CREATE DATABASE IF NOT EXISTS apartment_manager CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE apartment_manager;

CREATE TABLE IF NOT EXISTS apartments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  address VARCHAR(255) NOT NULL,
  area INT NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  available TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

